url: "https://hire.aubreypwd.com"
baseurl: ''
#ga: false

title: "Aubrey Portwood - Freelancer/Contractor - I build websites for people who don't want to mess around with one."

description: "For over a decade, I built websites and shipped high-stakes solutions for agencies and companies. Now I work independently as a freelancer/contractor, bringing that same experience directly to people and businesses who need a trusted web development guy in their corner."
keywords: WordPress developer, custom web development, senior WordPress developer, freelance web developer, contract web developer, WordPress contractor, WordPress freelancer, Albuquerque web developer, web developer New Mexico, Rio Rancho web developer, Las Cruces web developer, New Mexico static site developer, performance web developer, WordPress performance optimization, fast website development, core web vitals optimization, technical SEO support, search visibility optimization, WordPress custom plugins, website help & support, clear development guidance, practical web solutions, honest web developer, straight talk web help, long-term web support, developer in your corner, friendly web developer, jamstack developer, jamstack consultant, jamstack architect, jekyll developer, hugo developer, modern jamstack consulting, static jamstack sites, zero maintenance websites, unhackable websites, static site developer, platform-free websites, fast static site development, performance-first web design, senior freelance web partner, small business web consultant, remote web developer, transparent web consultant, local Albuquerque web consultant, local Rio Rancho web strategist, Las Cruces web partner
job_title: Freelance website developer and designer.

exclude:
  - .sublime-*
  - .vscode*
  - agents/
  - .cursor*
  - exclude/
  - resources/
  - TODO.md

timezone: America/Denver

plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-toc

toc:
  max_level: 2

email: aubreypwd@icloud.com

sidebar:
  animate_messages: false
  message_speed: 2.5
  messages:
    - I don't want a website to be a **headache.**
    - That's why I build websites _differently._
    - They're designed to **get out of your way**
    - More than a **decade** of experience has taught me **that's what people really want!**
  social:
    - name: "I'm on Twitter/X"
      url: "https://twitter.com/aubreypwd"
      fa: "twitter"
    - name: "View my LinkedIn profile"
      url: "https://www.linkedin.com/in/aubreypwd"
      fa: "linkedin-in"
    - name: "See my code on Github"
      url: "https://github.com/aubreypwd"
      fa: "github"
    - name: "View my WordPress.org profile"
      url: "https://profiles.wordpress.org/aubreypwd"
      fa: "wordpress"
    - name: "I'm also on Mastodon"
      url: "https://mastodon.social/@aubreypwd"
      fa: "mastodon"
