url: "https://hire.aubreypwd.com"
baseurl: "/"
title: "Aubrey Portwood - Freelancer/Contractor - I want to be your goto web guy."
description: "For over a decade, I built websites and shipped high-stakes solutions for agencies and companies. Now I work independently as a freelancer/contractor, bringing that same experience directly to people and businesses who need a trusted web development guy in their corner. Someone who cuts through the hype, explains things clearly, and helps you build practical solutions that actually fit your mission and goals. No BS, no pressureâ€”just solid work and honest guidance from someone who's seen it all."
keywords: WordPress developer, custom web development, senior WordPress developer, freelance web developer, contract web developer, WordPress contractor, WordPress freelancer, Albuquerque web developer, web developer New Mexico, performance web developer, WordPress performance optimization, fast website development, core web vitals optimization, technical SEO support, search visibility optimization, WordPress custom plugins, website help & support, clear development guidance, practical web solutions, honest web developer, straight talk web help, long-term web support, developer in your corner, friendly web developer
exclude:
  - .sublime-*
  - .vscode*
  - agents/
  - .cursor*
  - exclude/
  - resources/
timezone: America/Denver
plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-toc
toc:
  max_level: 2http://127.0.0.1:4000/assets/images/resources/comp-img4.png
email: aubreypwd@icloud.com
sidebar:
  animate_messages: false
  messages:
    - "You know that **web guy** you wish had time to help...but they just **couldn't** because they were working a 9-5?"
    - "For over a decade, that was me! But now I'm working as a **freelancer.**"
    - "And, I want to help you! Just [text me](sms:+13142827391)"
    - "Or [email me](mailto:hello@aubreypwd.com)"
