title: "Aubrey Portwood - Performance-first web developer"
description: "Aubrey Portwood is a web developer that builds with a performance-first mindset from start to finish with over a decade of experience."
email: "nobody@example.com"
baseurl: ""
url: ""
destination: docs
job_title: Performance-first web developer
keywords: custom web development, wordpress expert, wordpress performance, seo expert albuquerque, senior wordpress developer, web developer new mexico, performance web developer, fast website, core web vitals, custom wordpress plugins, albuquerque web developer, wordpress speed optimization, technical seo, php developer, new mexico websites
default_domain: hire.aubreypwd.com
exclude:
  - .sublime-workspace
